AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - extra/*
    - gemfiles/*
    - spec/**/*

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 22

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30

Style/SignalException:
  EnforcedStyle: only_raise

Style/RaiseArgs:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'lib/health_monitor/providers/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
