---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*
    - extra/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/BlockDelimiters:
  AllowedPatterns: ['expect']

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 125
  Exclude:
    - spec/**/*

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

#########
# RSPEC #
#########

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Enabled: false

RSpecRails/HttpStatus:
  EnforcedStyle: numeric

RSpec/AnyInstance:
  Enabled: false
